export const stateMexico = [
    {_id:'Aguascalientes', nombre:'Aguascalientes'},
    {_id:'Baja California', nombre:'Baja California'},
    {_id:'Baja California Sur', nombre: 'Baja California Sur'},
    {_id:'Campeche', nombre:'Campeche'},
    {_id:'Chiapas', nombre:'Chiapas'},
    {_id:'Chihuahua', nombre:'Chihuahua'},
    {_id:'Coahuila de Zaragoza', nombre:'Coahuila de Zaragoza'},
    {_id:'Colima', nombre:'Colima'},
    {_id:'Ciudad de México', nombre:'Ciudad de México'},
    {_id:'Durango', nombre:'Durango'},
    {_id:'Guanajuato', nombre:'Guanajuato'},
    {_id:'Guerrero', nombre:'Guerrero'},
    {_id:'Hidalgo', nombre:'Hidalgo'},
    {_id:'Jalisco', nombre:'Jalisco'},
    {_id:'México', nombre:'México'},
    {_id:'Michoacán de Ocampo', nombre:'Michoacán de Ocampo'},
    {_id:'Morelos', nombre:'Morelos'},
    {_id:'Nayarit', nombre:'Nayarit'},
    {_id:'Nuevo León', nombre:'Nuevo León'},
    {_id:'Oaxaca', nombre:'Oaxaca'}, 
    {_id:'Puebla', nombre:'Puebla'},
    {_id:'Querétaro', nombre:'Querétaro'},
    {_id:'Quintana Roo', nombre:'Quintana Roo'},
    {_id:'San Luis Potosí', nombre:'San Luis Potosí'},
    {_id:'Sinaloa', nombre:'Sinaloa'},
    {_id:'Sonora', nombre:'Sonora'},
    {_id:'Tabasco', nombre:'Tabasco'},
    {_id:'Tamaulipas', nombre:'Tamaulipas'},
    {_id:'Tlaxcala', nombre:'Tlaxcala'},
    {_id:'Veracruz de Ignacio de la Llave', nombre:'Veracruz de Ignacio de la Llave'},
    {_id:'Yucatán', nombre:'Yucatán'},
    {_id:'Zacatecas', nombre:'Zacatecas'},

]